# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org


- name: setup prompt
  ansible.builtin.shell: set-prompt github runner

- name: add github runner user
  ansible.builtin.user:
    name: nrunner


- name: create github directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
  owner: nrunner
  group: nrunner

- name: Download & Extract extract runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes
  owner: nrunner
  group: nrunner


- name: Grab Token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/Nazrinakhan/actions/runners/registration-token | jq .token
  register: out
  become_user: ec2-user

- name: Install libicu deendency
  ansible.builtin.dnf:
    name: libicu
    state: latest

- name: configure github runner
  ansible.builtin.shell: ./config.sh --url https://github.com/Nazrinakhan --token {{ token.stdout }} --runnergroup Default --name ec2 --labels rhel --work _work --replace
  args:
    chdir: /actions-runner
  become_user: nrunner