# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org

- name: Setup prompt
  ansible.builtin.shell: set-prompt github runner

- name: Add GitHub runner user
  ansible.builtin.user:
    name: grunner
    state: present

- name: Create GitHub directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: grunner

- name: Download & Extract GitHub runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes
  owner: grunner
  group: grunner

- name: Grab Token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/raghudevopsb80/actions/runners/registration-token | jq -r .token
  register: token
  become_user: ec2-user

- name: Install libicu dependency
  ansible.builtin.dnf:
    name: libicu
    state: latest

- name: Configure GitHub runner
  ansible.builtin.shell: ./config.sh --url https://github.com/Nazrinakhan --token {{ token.stdout }} --runnergroup Default --name ec2 --labels rhel --work _work --replace
  args:
    chdir: /actions-runner
  become_user: grunner
  register: config_result

- name: Print configuration result
  ansible.builtin.debug:
    msg: "Configuration result: {{ config_result.stdout }}"
